version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: mockly_postgres
    restart: always
    environment:
      POSTGRES_USER: mockly_user
      POSTGRES_PASSWORD: mockly_password
      POSTGRES_DB: mockly_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
