spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mockly_db
    username: mockly_user
    password: mockly_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8080
